### ISSUE TITLE
Track#2

### ISSUE THREAD

**Issue by pablanopete** [status-im/ETHDenver#3]
**Top DApps WebApp** 

Motivation:
Currently there is no real easy way to identify which DApps are frequently / most being used in the ecosystem. You can mostly browse subreddits, or check StateOfTheDApps to find out about current trending DApps though these are not telling or efficient enough for the world's largest decentralized computer. While there is a longer term goal for Status to have a curation market, we would like to see some creative ways to display DApp usage in the interim and encourage hackers to learn about Ethereum more!

Description:
Create a simple web app for Status to display / analyze the most popular DApp contracts by Gas Usage or other interesting metric you come up with. Demonstrate efficient approaches or methods to approach this problem using either an API or running a node yourself and innovative methodologies.  

Acceptance Criteria:

Webapp clearly and simply shows top #X DApp with concise metrics to back up popularity of usage 
Open-source code 
Interface is clean and compelling / mobile responsive
Creative solution
Technical merit

Hints:
https://etherscan.io/apis
https://github.com/sebs/etherscan-api
https://ethgasstation.info/gasguzzlers.php
https://www.stateofthedapps.com

Judges: Ricardo, Adam 

Prerequisites:
Please keep repository fork public

Instructions for teams working on bounties for Status,

1.) Fork this repository
2.) Clone your fork and create a new branch with the naming convention `teamname-issue-ISSUE_NUMBER`
3.) Add all source code, commit and push to your branch
4.) Navigate to your fork repo and create a PR from your `teamname-issue-ISSUE_NUMBER` branch to ETHDenver repo with `master` branch as base branch.

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x334c282f3f1cffd6d924e88ad155e9924d14f9c7](https://etherscan.io/address/0x334c282f3f1cffd6d924e88ad155e9924d14f9c7)
![QR Code](https://openbounty.status.im/qr/status-im/ETHDenver/bounty/3/c30979ed19c7555e0e43fab28337559e8f8a3fb9a7eaf3580ed8f31f5e7178af/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
